name: aura-chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - flask
    - flask-socketio
    - flask-cors
    - google-generativeai
    - pymongo[srv]
    - python-dotenv
    - cryptography
    - eventlet
